### ISSUE TITLE
Formulas longer than size "n"

### ISSUE THREAD

**Issue by thechrisu** [Maaarcocr/validator#1]
Hirsch implicitly reduced the maximum formula length to 50 in his skeleton file by just allocating only 50 chars for one formula. Currently, the validator partially gives me longer formulas, thus cutting off the end of the formula, thus causing a parsing error. In an ideal world, of course a formula of every length should be acceptable. However, I believe it makes sense to introduce an upper limit on the formula length for the purpose of this assignment.

**Comment by Maaarcocr** [comment]
Thanks Chris! I will try to fix this asap!

**Comment by Maaarcocr** [comment]
@culshoefer: Solved!
