### ISSUE TITLE
On CentOS 5, $OSNAME is different

### ISSUE THREAD

**Issue by thechrisu** [Maaarcocr/validator#2]
$OSNAME on CentOS 5 (our lab machines) gives 'linux', and thus the if does not work. Actually, if you want to get to the bottom of this, on our lab machines, there are a few unmet dependencies...

**Comment by Maaarcocr** [comment]
I will update the script.sh file to accommodate this.
I will compile the file in such a way it will not need any dependencies, this will only work on Linux though. 
Thanks @culshoefer for pointing this out.

**Comment by Maaarcocr** [comment]
Solved it!
